<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>Planalyzer.Gui</AssemblyName>
    <RootNamespace>Planalyzer.Gui</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.1" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Planalyzer.Core\Planalyzer.Core.csproj" />
    <ProjectReference Include="..\Planalyzer.Comparison\Planalyzer.Comparison.csproj" />
    <ProjectReference Include="..\Planalyzer.Execution\Planalyzer.Execution.csproj" />
    <ProjectReference Include="..\Planalyzer.Validation\Planalyzer.Validation.csproj" />
  </ItemGroup>
</Project>
