<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>planalyzer</AssemblyName>
    <RootNamespace>Planalyzer.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Planalyzer.Core\Planalyzer.Core.csproj" />
    <ProjectReference Include="..\Planalyzer.Comparison\Planalyzer.Comparison.csproj" />
    <ProjectReference Include="..\Planalyzer.Execution\Planalyzer.Execution.csproj" />
  </ItemGroup>
</Project>
